### ISSUE TITLE
on 0.6.1, the ember-source peer has an incorrect version

### ISSUE THREAD

**Issue by NullVoxPopuli** [tildeio/ember-element-helper#100]
https://github.com/tildeio/ember-element-helper/blob/v0.6.1/package.json#L76

it says `|| 4`, which works under yarn, but we found in other packages that it needs to be `|| ^4.0.0` -- which allows pnpm to do the right thing

**Comment by boris-petrov** [comment]
@NullVoxPopuli - I think this has been fixed in the new version. So you can close the issue. However, the release hasn't reached npm yet. Can you check?

**Comment by NullVoxPopuli** [comment]
appears so. I was following the RELEASE.md, and I suppose I shouldn't have, as this repo has a different release setup -- I'll resolve

**Comment by NullVoxPopuli** [comment]
It should be published now! https://www.npmjs.com/package/ember-element-helper?activeTab=code yay!!

_and_ the automated publish is fixed. yay!
