### ISSUE TITLE
Ember-source for addon is incompatible with ember 5.0.0

### ISSUE THREAD

**Issue by Elawphant** [tildeio/ember-element-helper#104]
npm ERR! Could not resolve dependency:
npm ERR! peer ember-source@"^3.8 || 4" from ember-element-helper@0.6.1
npm ERR! node_modules/ember-element-helper
npm ERR!   dev ember-element-helper@"^0.6.1" from the root project

**Comment by mkszepp** [comment]
@chancancode it would be great to get a release which supports ember v5 (PR with necessary changes opened)
