### ISSUE TITLE
Is anyone successfully using ember-element-helper with Vite?

### ISSUE THREAD

**Issue by trevordevore** [tildeio/ember-element-helper#122]
I'm recreating an Ember app using the https://github.com/embroider-build/app-blueprint blueprint, which uses Embroider + Vite. The current version of the app uses Embroider + Webpack. The following code works in the Embroider + Webpack version, but not the Embroider + Vite version.

```
{{#let (element this.elementTag) as |Tag|}}
  <Tag ...attributes>
    <span '{{this.spinnerCssClasses}}'></span>
  </Tag>
{{/let}}
```

The following error appears in the console with the Embroider + Vite app:

```
TypeError: Class constructor ElementHelper cannot be invoked without 'new'
```

Any ideas?

**Comment by NullVoxPopuli** [comment]
How recently did you generate your project?
What node version are you using?
What package manager are you using? 

I used:
- node 22+
- pnpm 9.15+

I have a TS project from yesterday that works:

![image](https://github.com/user-attachments/assets/85b78571-c78d-44de-8d39-45c15860eff9)

I also just made a brand new project (juts now!)
and it worked as well
![image](https://github.com/user-attachments/assets/91f43c33-9609-469f-872f-45a28978ff82)

**Comment by trevordevore** [comment]
And I generated the Ember app yesterday.

**Comment by trevordevore** [comment]
I think the problem was with pnpm. After updating pnpm from 9.12 to 9.15, deleting node_modules, and clearing the pnpm store cache ember-element-helper works with both node 18 and node 22.

**Comment by trevordevore** [comment]
The problem was not pnpm, but rather how a v2 addon was configured.

1. `ember-element-helper` is being used in a v2 addon.
2. The `test-app` in the v2 addon listed the addon as a `devDependency`.
3. Moving the addon to a `dependency` of the `test-app` and injecting the addon fixed the run-time error being triggered by ember-element-helper.

See https://pnpm.io/package_json#dependenciesmetainjected

In `test-app` package.json`:

```
  "dependenciesMeta": {
    "my-addon": {
      "injected": true
    }
  },
```
