### ISSUE TITLE
Is Embroider support on the roadmap?

### ISSUE THREAD

**Issue by tansongyang** [tildeio/ember-element-helper#30]
We have an application that uses this helper. After getting past some other issues, we were able to build the app with Embroider. Then we turned on `staticHelpers`, and builds were failing until we removed references to `(element ...)`. One was a reference to `(element this.tag)` and the other was `(element '')`.

Is this known? Is Embroider support on the roadmap?

**Comment by simonihmig** [comment]
Same here. Created a PR to add compatibility support in Embroider: https://github.com/embroider-build/embroider/pull/536
