### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by amk221** [tildeio/ember-element-helper#37]
Are there any performance optimisations that can be made? 

Asking because, I'd like the ability to be able to chose a tag, but not at the expense of a slower component if I decide _not_ to chose a tag.

I'm trying to avoid something like:

```hbs
{{! my-component.hbs}}
{{#if @tag}}
  {{#let (element @tag) as |Tag|}}
    <Tag></Tag>
  {{/let}}
{{else}}
  <div></div>
{{/if}}
```

Given

```hbs
{{#each this.oneThousandItems}}
  <MyComponent />
{{/each}}
```

```hbs
{{#each this.oneThousandItems}}
  <MyComponent @tag="button" />
{{/each}}
```

Although the above looks fine, one has to duplicate actions and attributes etc placed on `<Tag>`, and `<div>`.

Thanks for any insight.

I'm seeing a decrease in speed from ~400ms to render to ~700ms

**Comment by betocantu93** [comment]
I went as far as https://github.com/prysmex/ember-eui/blob/master/packages/core/addon/components/text-block/index.hbs... performance matters for UI components, I guess it depends, as always.

**Comment by amk221** [comment]
@betocantu93 ooh, that's a nice styleguide.

**Comment by betocantu93** [comment]
:D thanks! its mostly template only components and glimmer classes when needed, so its fast!!

**Comment by chancancode** [comment]
In your case if it really matters (and that you benchmarked it to confirm it’s worth it), then you can wrap your snippet into a <MaybeElement> template-only component, and that shouldn’t add too much overhead while avoiding your duplication issue
