### ISSUE TITLE
Cant set attributes

### ISSUE THREAD

**Issue by emattias** [tildeio/ember-element-helper#68]
I wanted to `yield` a `span` from a general component and set some classes and maybe other attributes on the span for consumers of the general component. Something like this:

```
{{yield
  (hash
    Foo=(element "span" class="truncate")
  )
}}
```

But its [explicitly not allowed](https://github.com/tildeio/ember-element-helper/blob/main/addon/helpers/-element.js#L19). How come? And could it be changed to be allowed?

**Comment by SergeAstapov** [comment]
@emattias to pass class name, you may try

```hbs
{{yield
  (hash
    Foo=(component (element "span") class="truncate")
  )
}}
```

Other attributes can't be passed in and it's not limitation of this addon but rather a limitation of Ember.js at this point of time, see for more info https://github.com/emberjs/rfcs/issues/497

**Comment by angelayanpan** [comment]
component helper seems to be adding `@` to `class`
