### ISSUE TITLE
Doesn't work in an engine?

### ISSUE THREAD

**Issue by luketheobscure** [tildeio/ember-element-helper#7]
I'm not sure this is the right repo to file a bug, but I think this addon is broken when used in an engine. I've got an unusual setup though, so it might be something else.

Basically when the dynamic element is invoked (it's being called from ember-basic-dropdown) I get `Error: Could not find module '<my engine name>/components/-dynamic-element' imported from '(require)'`. 

Following the stack trace up, it looks like the engine file has the line `define.alias("@ember/component", "<my engine name>/components/-dynamic-element");`. When `findModule` runs, it tried to resolve `@ember/component`, but that isn't in the registry.

This is using ember and ember-cli 3.11.

**Comment by luketheobscure** [comment]
After doing some more debugging, I'm starting to think this is an issue with ember-engines. Please feel free to close this issue, unless you think it's still an issue.

**Comment by dguettler** [comment]
@luketheobscure did you make any progress resolving this? I'm stuck with the same issue.
I created a minimal test scenario here https://github.com/dguettler/ember-dynamic-element it only has one route in the main application and one in the in-repo-engine.
`power-select` renders just fine in the main application, but fails when called in the engine's template.

**Comment by dguettler** [comment]
here https://github.com/dguettler/ember-dynamic-element/tree/ember-element-helper-only is a branch which only uses `ember-element-helper`. It has the same issue.

**Comment by dguettler** [comment]
@luketheobscure just FYI, downgrading to `ember-power-select@2.3.5` is a possible workaround for now as it doesn't use `ember-element-helper`

**Comment by rwjblue** [comment]
Submitted https://github.com/tildeio/ember-element-helper/pull/8 to address this issue.

**Comment by luketheobscure** [comment]
@dguettler: I forked ember-basic-dropdown to remove the dependency. Here's the commit if you're interested – https://github.com/luketheobscure/ember-basic-dropdown/commit/ece0e2616351c8a393f415573590408deea7f611

@rwjblue: ❤️
