### ISSUE TITLE
Expected a dynamic component definition, but received an object or function that did not have a component manager associated with it.

### ISSUE THREAD

**Issue by NullVoxPopuli** [tildeio/ember-element-helper#89]
Presentnly getting this error:

```
Uncaught (in promise) Error: Expected a dynamic component definition, 
but received an object or function that did not have a component manager associated with it. 
The dynamic invocation was `<(result of a `(helper function findElement)` helper)>` 
or `{{(result of a `(helper function findElement)` helper)}}`, 
and the incorrect definition is the value at the path `(result of a `(helper function findElement)` helper)`, 
which was: HTMLDivElement
    <anonymous> runtime.js:3021
```

Has something gone wrong with a transform?
I'm using embroider.
```
❯ pnpm why ember-element-helper

dependencies:
ember-container-query 2.1.0
└── ember-element-helper 0.6.1
ember-element-helper 0.6.1
ember-headlessui 0.13.0
└── ember-element-helper 0.6.1

```

Happens on ember-source 4.4 and 4.5

**Comment by chancancode** [comment]
I also don’t know that this is really related to this addon? According to the message it seems like you have something along the lines of `<Foo />` where `Foo` came from `(findElement …)` which isn’t really something this addon provides?

**Comment by NullVoxPopuli** [comment]
> which isn’t really something this addon provides?

well, `findElement` isn't anything in ContainerQuery -- search https://github.com/ijlee2/ember-container-query/search?q=findElement

I've locally logged what `Tag` is, and it is an HTMLDivElement, which, to me, seems like this library should maybe provide a component manager for HTMLElements? maybe? What is the intent with HTMLElements as values in `<ComponentSyntax />`?

**Comment by NullVoxPopuli** [comment]
ah yes, something goofy is going on, because what I have at runtime does not match that implementation (at all)

![image](https://user-images.githubusercontent.com/199018/179617635-de80f1f8-8223-4092-8c78-0b0b9c2bf244.png)
